version: "3.7"

x-common:
  - &DB_PASS "test"
  - &DB_USER "test"
  - &DB_NAME "testdb"
  - &WORKUSR "app"

services:
  frontend-angular:
    image: kudoshunsuke/angular-dailyreport
    build:
      context: ./frontend-angular
      dockerfile: ./Dockerfile
      args:
        WORKUSR: node

    ports:
      - "18080:8080"
    tty: true
    command: bash
    volumes:
      - ./frontend-angular/src:/home/node/frontapp/src
    #  - ./frontend-angular/package.json:/home/node/frontapp/package.json
    #  - ./frontend-angular/tsconfig.json:/home/node/frontapp/tsconfig.json
    depends_on:
      - db
      - backend

  frontend-vuejs:
    image: kudoshunsuke/vue-dailyreport
    build:
      context: ./frontend-vuejs
      dockerfile: ./Dockerfile
      args:
        WORKUSR: node

    ports:
      - "18080:8080"
    tty: true
    command: bash
    volumes:
      - ./frontend-vuejs/src:/home/node/frontapp/src
      - ./frontend-vuejs/package.json:/home/node/frontapp/package.json
      - ./frontend-vuejs/tsconfig.json:/home/node/frontapp/tsconfig.json
      - ./frontend-vuejs/vue.config.js:/home/node/frontapp/vue.config.js
      - ./frontend-vuejs/yarn.lock:/home/node/frontapp/yarn.lock

  frontend:
    image: kudoshunsuke/react-dailyreport
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "18080:8080"
    tty: true
    command: bash
    volumes:
      - ./frontend/src:/home/node/frontapp/src
      - ./frontend/package.json:/home/node/frontapp/package.json
    environment:
      PORT: 8080

  backend:
    image: kudoshunsuke/golang-echo:1.14-buster
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      args:
        WORKUSR: *WORKUSR

    depends_on:
      - db
    environment:
      DB_NAME: *DB_NAME
      DB_USER: *DB_USER
      DB_PASS: *DB_PASS
      DB_HOST: db
      DB_PORT: 3306
      WORKUSR: *WORKUSR
      TESTING: 1
      TZ: Tokyo/Asia
    volumes:
      - ./backend/app:/home/app/app
      - ./backend/entrypoint.sh:/entrypoint.sh
    command: ["go", "run", "server.go"]
    entrypoint: /entrypoint.sh
    tty: true
    ports:
      - "13000:3000"

  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: 'maria'
      MYSQL_DATABASE: *DB_NAME
      MYSQL_USER: *DB_USER
      MYSQL_PASSWORD: *DB_PASS
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      MYSQL_INITDB_SKIP_TZINFO: 'yes'
      TZ: Tokyo/Asia

    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "23306:3306"

volumes:
  mysql:
    driver: "local"

